(require 'org)
(load-file "org-mindmap.el")
(load-file "org-mindmap-parser.el")

(defun org-mindmap--trace-path (lines row col moving-dir visited)
  (let ((nodes-found nil)
        (running t))
    (while running
      (if (or (< row 0) (>= row (length lines))
              (< col 0) (>= col (length (aref lines row))))
          (setq running nil)
        (if (gethash (cons row col) visited)
            (setq running nil)
          (puthash (cons row col) t visited)
          (let* ((char (org-mindmap--grid-get lines row col))
                 (new-pos nil))
            (if (org-mindmap--is-whitespace char)
                (let ((next-row (+ row (cdr moving-dir)))
                      (next-col (+ col (car moving-dir))))
                  (if (org-mindmap--accepts-entry-p lines next-row next-col moving-dir)
                      (setq row next-row col next-col)
                    (setq new-pos (org-mindmap--recover-connection lines row col moving-dir))
                    (if new-pos
                        (setq row (car new-pos) col (cdr new-pos))
                      (setq row next-row col next-col))))
              (if (not (org-mindmap--is-connector char))
                  (let* ((parsed (org-mindmap--parse-text-node lines row col moving-dir visited))
                         (node (car parsed))
                         (next-col (cdr parsed)))
                    (when next-col
                      (let ((children (org-mindmap--trace-path lines row next-col moving-dir visited)))
                        (dolist (child children)
                          (setf (org-mindmap-node-parent child) node))
                        (setf (org-mindmap-node-children node) children)))
                    (push node nodes-found)
                    (setq running nil))
                (let* ((entry-port (org-mindmap--invert-dir moving-dir))
                       (char-ports (copy-sequence (gethash char org-mindmap-ports))))
                  (if (not (member entry-port char-ports))
                      (setq running nil)
                    (setq char-ports (remove entry-port char-ports))
                    (cond
                     ((= (length char-ports) 0)
                      (setq running nil))
                     ((= (length char-ports) 1)
                      (setq moving-dir (car char-ports)
                            col (+ col (car moving-dir))
                            row (+ row (cdr moving-dir))))
                     (t
                      (dolist (branch-dir char-ports)
                        (let* ((b-row (+ row (cdr branch-dir)))
                               (b-col (+ col (car branch-dir)))
                               (branch-nodes (org-mindmap--trace-path lines b-row b-col branch-dir visited)))
                          (setq nodes-found (append nodes-found branch-nodes))))
                      (setq running nil)))))))))))
    (nreverse nodes-found)))

(let ((lines (vconcat '("┬─ Root ┬─ Node A"
                        "        ├─ Node B"
                        "        ╰─ Node C")))
      (visited (make-hash-table :test 'equal)))
  (let ((roots (org-mindmap--trace-path lines 0 0 org-mindmap-dir-right visited)))
    (print (mapcar #'org-mindmap-node-text (org-mindmap-node-children (car roots))))))
